## Curso: Análise e Desenvolvimento de Sistemas

## Disciplina:  DISRUPTIVE ARCHITECTURES: IOT, IA & GENERATIVE AI

## Turmas: 2TDS (1o semestre de 2026)

## Professor: André Tritiack

----------------------

## **Diagnóstico médico: Problemas Ortopédicos na Coluna Vertebral**

Esse dataset contém dados sobre problemas ortopédicos na coluna vertebral, diagnosticados no Centre Médico-Chirurgical de Réadaptation des Massues, em Lyon, France. Contém 6 atributos biomecânicos para 310 entradas anonimizadas, sendo 100 de pacientes considerados sem problemas (Normal - NO), 60 de pacientes com Hérnia de Disco (Disk Hernia - DH) e 150 de pacientes com Espondilolistese (Spondylolisthesis - SL).

Maiores informações disponíveis em https://www.openml.org/d/1523

Escolha dois algoritmos para treinar seus modelos de classificação.

Opções: KNN, Random Forest, Decision Tree, Logistic Regression, SVM

In [7]:
import pandas as pd
df = pd.read_csv("../questao_01.csv")
df.head()

,Unnamed: 0,V1,V2,V3,V4,V5,V6,diagnostic
0,0,63.027818,22.552586,39.609117,40.475232,98.672917,-0.254400,Disk Hernia
1,1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,Disk Hernia
2,2,68.832021,22.218482,50.092194,46.613539,105.985136,-3.530317,Disk Hernia
3,3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,Disk Hernia
4,4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,Disk Hernia

In [8]:
df.shape

(310, 8)

In [9]:
df.head(10)

,Unnamed: 0,V1,V2,V3,V4,V5,V6,diagnostic
0,0,63.027818,22.552586,39.609117,40.475232,98.672917,-0.254400,Disk Hernia
1,1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,Disk Hernia
2,2,68.832021,22.218482,50.092194,46.613539,105.985136,-3.530317,Disk Hernia
3,3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,Disk Hernia
4,4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,Disk Hernia
5,5,40.250200,13.921907,25.124950,26.328293,130.327871,2.230652,Disk Hernia
6,6,53.432928,15.864336,37.165934,37.568592,120.567523,5.988551,Disk Hernia
7,7,45.366754,10.755611,29.038349,34.611142,117.270068,-10.675871,Disk Hernia
8,8,43.790190,13.533753,42.690814,30.256437,125.002893,13.289018,Disk Hernia
9,9,36.686353,5.010884,41.948751,31.675469,84.241415,0.664437,Disk Hernia

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  310 non-null    int64
 1   V1          310 non-null    float64
 2   V2          310 non-null    float64
 3   V3          310 non-null    float64
 4   V4          310 non-null    float64
 5   V5          310 non-null    float64
 6   V6          310 non-null    float64
 7   diagnostic  310 non-null    object
dtypes: float64(6), int64(1), object(1)
memory usage: 19.5+ KB

In [11]:
df.describe()

,Unnamed: 0,V1,V2,V3,V4,V5,V6
count,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000
mean,154.500000,60.496653,17.542822,51.930930,42.953831,117.920655,26.296694
std,89.633513,17.236520,10.008330,18.554064,13.423102,13.317377,37.559027
min,0.000000,26.147921,-6.554948,14.000000,13.366931,70.082575,-11.058179
25%,77.250000,46.430294,10.667069,37.000000,33.347122,110.709196,1.603727
50%,154.500000,58.691038,16.357689,49.562398,42.404912,118.268178,11.767933
75%,231.750000,72.877696,22.120395,63.000000,52.695889,125.467675,41.287352
max,309.000000,129.834041,49.431864,125.742386,121.429566,163.071041,418.543082

In [ ]:
#Baixar no terminal: "pip install scikit-learn" e "conda install scikit-learn"

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["diagnostic"] = le.fit_transform(df["diagnostic"])

In [17]:
df["diagnostic"].value_counts()

diagnostic
2    150
1    100
0     60
Name: count, dtype: int64

Crie as variáveis X e y.

X deve ser um dataframe que contenha os dados dos seis atributos referentes aos biomarcadores (V1 a V6).

y deve ser um array com os dados da coluna "diagnostic".

In [18]:
#X = atributos
X = df[["V1", "V2", "V3", "V4", "V5", "V6"]]

In [19]:
#y = alvo
y = df["diagnostic"]

In [20]:
#primeiros registros de X
X.head()

          V1         V2         V3         V4          V5         V6
0  63.027818  22.552586  39.609117  40.475232   98.672917  -0.254400
1  39.056951  10.060991  25.015378  28.995960  114.405425   4.564259
2  68.832021  22.218482  50.092194  46.613539  105.985136  -3.530317
3  69.297008  24.652878  44.311238  44.644130  101.868495  11.211523
4  49.712859   9.652075  28.317406  40.060784  108.168725   7.918501

In [21]:
#X como numpy
X.values

array([[ 63.027818,  22.552586,  39.609117,  40.475232,  98.672917,
         -0.2544  ],
       [ 39.056951,  10.060991,  25.015378,  28.99596 , 114.405425,
          4.564259],
       [ 68.832021,  22.218482,  50.092194,  46.613539, 105.985136,
         -3.530317],
       ...,
       [ 61.446597,  22.694968,  46.170347,  38.751628, 125.670725,
         -2.70788 ],
       [ 45.252792,   8.693157,  41.583126,  36.559635, 118.545842,
          0.21475 ],
       [ 33.841641,   5.073991,  36.641233,  28.767649, 123.945244,
         -0.199249]], shape=(310, 6))

In [22]:
#y como numpy
y.values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

Abaixo, separe 70% dos dados para treinamento e 30% para teste.

Utilize os nomes X_train, X_test, y_train e y_test

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

In [24]:
from sklearn.tree import DecisionTreeClassifier
#criando modelo
modelo1 = DecisionTreeClassifier()

In [25]:
#treinando
modelo1.fit(X_train, y_train)

DecisionTreeClassifier()

In [26]:
#previsões
y_predict_1 = modelo1.predict(X_test)
y_predict_1

array([1, 0, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 1, 1, 2, 0, 2, 1, 2, 2, 0, 0, 2, 2, 1, 0, 2, 1,
       0, 2, 1, 0, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 0, 1, 2, 2, 2, 1, 0,
       2, 2, 2, 1, 0, 1, 2, 1, 1, 0, 0, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2,
       2, 1, 0, 2, 2])

In [27]:
from sklearn.neighbors import KNeighborsClassifier
#criando modelo
modelo2 = KNeighborsClassifier()

In [28]:
#treinar
modelo2.fit(X_train, y_train)

KNeighborsClassifier()

In [29]:
#previsões
y_predict_2 = modelo2.predict(X_test)

In [30]:
y_predict_2

array([1, 0, 1, 2, 0, 2, 2, 2, 0, 1, 2, 2, 0, 1, 1, 0, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 1, 1, 2, 0, 2, 1, 2, 2, 0, 1, 2, 2, 1, 0, 2, 1,
       1, 2, 1, 0, 1, 2, 2, 1, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 2, 1, 0,
       2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2,
       2, 1, 0, 2, 1])

In [31]:
from sklearn.metrics import accuracy_score
#acurácia modelo 1
acc1 = accuracy_score(y_test, y_predict_1)
print("Acurácia Modelo 1:", acc1)

Acurácia Modelo 1: 0.8064516129032258

In [32]:
from sklearn.metrics import accuracy_score
#acurácia modelo 2
acc2 = accuracy_score(y_test, y_predict_2)
print("Acurácia Modelo 2:", acc2)

Acurácia Modelo 2: 0.7849462365591398

In [33]:
#escolhendo modelo
if acc1 > acc2:
    modelo = modelo1
else:
    modelo = modelo2

In [34]:
import os
import pickle
#criando a pasta
os.makedirs("model", exist_ok=True)
#salvando modelo
with open("model/modelo.pkl", "wb") as f:
    pickle.dump(modelo, f)

## **Diagnóstico médico: Diabetes no povo Pima**

## Você pode construir um modelo de aprendizado de máquina para prever com precisão se os pacientes no conjunto de dados têm diabetes ou não?

Esse dataset contém dados sobre incidência de diabetes em mulheres do Povo Pima (índios nativos norte americanos originários do atual Estado do Arizona). Contém 8 atributos biomédicos para 768 entradas anonimizadas, sendo 500 testados negativo para diabetes e 268 testados positivo para diabetes.

Faça o download do dataset:

https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database


Utilize as técnicas e a mesma sequência e estrutura da primeira parte para desenvolver sua solução.

Escolha o algoritmo de sua preferência.

In [67]:
#Carregando o dataser
import pandas as pd
df_diabetes = pd.read_csv("diabetes.csv")
df_diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [68]:
#Verificar tamanho
df_diabetes.shape

(768, 9)

In [69]:
#Carregar informações
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [70]:
#Carregar estatísticas
df_diabetes.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [71]:
# X = todas as colunas
X = df_diabetes.drop("Outcome", axis=1)
# y = coluna alvo
y = df_diabetes["Outcome"]

In [72]:
#Partindo pra visualização:

In [55]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [56]:
X.values

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [57]:
y.values

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [73]:
#Separando treino
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

In [75]:
#Modelo 1: Árvore de decisão
from sklearn.tree import DecisionTreeClassifier
modelo1 = DecisionTreeClassifier()
modelo1.fit(X_train, y_train)
y_predict_1 = modelo1.predict(X_test)

In [76]:
#Modelo 2: KNN
from sklearn.neighbors import KNeighborsClassifier
modelo2 = KNeighborsClassifier()
modelo2.fit(X_train, y_train)
y_predict_2 = modelo2.predict(X_test)

In [77]:
#Visualizando previsões:

In [61]:
y_predict_1

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [62]:
y_predict_2

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [78]:
#Acurácia
from sklearn.metrics import accuracy_score
acc1 = accuracy_score(y_test, y_predict_1)
print("Acurácia Modelo 1:", acc1)
acc2 = accuracy_score(y_test, y_predict_2)
print("Acurácia Modelo 2:", acc2)

Acurácia Modelo 1: 0.696969696969697
Acurácia Modelo 2: 0.6883116883116883

In [103]:
#escolhendo o melhor modelo
if acc1 > acc2:
    modelo = modelo1
else:
    modelo = modelo2

In [104]:
import os
import pickle
os.makedirs("model", exist_ok=True)
with open("model/modelo_diabetes.pkl", "wb") as f:
    pickle.dump(modelo, f)

In [66]:
#O KNN foi o modelo escolhido por apresentar maior acurácia no conjunto de teste